
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC
 */
//1306170067 Esracan Güngör

class Kullanıcılar{
private String kullanici_adi;
private String parola;

    public String getKullanici_adi() {
        return kullanici_adi;
    }

    public void setKullanici_adi(String kullanici_adi) {
        this.kullanici_adi = kullanici_adi;
    }

    public String getParola() {
        return parola;
    }

    public void setParola(String parola) {
        this.parola = parola;
    }

    public Kullanıcılar(String kullanici_adi, String parola) {
        this.kullanici_adi = kullanici_adi;
        this.parola = parola;
    }

}
public class KitapSatisSitesi extends javax.swing.JFrame {
private static ArrayList<Kullanıcılar> kullanıcı_listesi=new ArrayList<Kullanıcılar>();

    public static ArrayList<Kullanıcılar> getKullanıcı_listesi() {
        return kullanıcı_listesi;
    }

    public static void setKullanıcı_listesi(ArrayList<Kullanıcılar> kullanıcı_listesi) {
        KitapSatisSitesi.kullanıcı_listesi = kullanıcı_listesi;
    }
    /**
     * Creates new form KitapSatisSitesi
     */
    public KitapSatisSitesi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        registerpaneli = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kitapsecenekleri = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ekitap = new javax.swing.JComboBox<>();
        sepetbutonu = new javax.swing.JButton();
        siparisverbutonu = new javax.swing.JButton();
        uyegirispaneli = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kullanici_adi_alani = new javax.swing.JTextField();
        parola_alani = new javax.swing.JPasswordField();
        uyeolbutonu = new javax.swing.JButton();
        girisyapbutonu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        registerpaneli.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout registerpaneliLayout = new javax.swing.GroupLayout(registerpaneli);
        registerpaneli.setLayout(registerpaneliLayout);
        registerpaneliLayout.setHorizontalGroup(
            registerpaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        registerpaneliLayout.setVerticalGroup(
            registerpaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("50TL VE ÜZERİ ALIŞVERİŞLERİNİZİ İÇİN KARGO BEDAVA");

        kitapsecenekleri.setBackground(new java.awt.Color(204, 204, 255));
        kitapsecenekleri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategoriler", "Araştırma - Tarih", "Bilim", "Çizgi Roman", "Ders / Sınav Kitapları", "Din - Mitoloji", "Edebiyat", "Eğitim Başvuru", "Felsefe", "Foreign Languages", " " }));
        kitapsecenekleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapsecenekleriActionPerformed(evt);
            }
        });

        jLabel2.setText("KİTAP ");

        jLabel3.setText("E-KİTAP");

        jLabel4.setText("Sepetim");

        ekitap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KATEGORİLER", "Edebiyat Dışı", "Biyografi ve Anı", "İş Dünyası ve Finans", "Karikatürler ve Çizgi Romanlar", "Çocuk ve Genç", "Edebiyat", "Polisiye ve Şüphe", "Bilim Kurgu ve Fantastik", "Sağlık ve Bakım", "Kurgu ve Edebiyat" }));
        ekitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekitapActionPerformed(evt);
            }
        });

        sepetbutonu.setText("Sepetime Git");
        sepetbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepetbutonuActionPerformed(evt);
            }
        });

        siparisverbutonu.setText("Sipariş Ver");
        siparisverbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparisverbutonuActionPerformed(evt);
            }
        });

        uyegirispaneli.setBackground(new java.awt.Color(153, 204, 255));
        uyegirispaneli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setText("Kullanici Adi:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Parola");

        uyeolbutonu.setText("ÜYE OL");
        uyeolbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeolbutonuActionPerformed(evt);
            }
        });

        girisyapbutonu.setText("GİRİŞ YAP");
        girisyapbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisyapbutonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uyegirispaneliLayout = new javax.swing.GroupLayout(uyegirispaneli);
        uyegirispaneli.setLayout(uyegirispaneliLayout);
        uyegirispaneliLayout.setHorizontalGroup(
            uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uyegirispaneliLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(uyegirispaneliLayout.createSequentialGroup()
                        .addGroup(uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uyeolbutonu))
                        .addGap(61, 61, 61)
                        .addGroup(uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uyegirispaneliLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(girisyapbutonu))
                            .addGroup(uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(kullanici_adi_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(parola_alani)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        uyegirispaneliLayout.setVerticalGroup(
            uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uyegirispaneliLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kullanici_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(parola_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uyegirispaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uyeolbutonu)
                    .addComponent(girisyapbutonu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0000000105409-1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kitapsecenekleri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(ekitap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sepetbutonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(siparisverbutonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(274, 274, 274)))
                        .addComponent(uyegirispaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kitapsecenekleri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ekitap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sepetbutonu)
                                .addGap(2, 2, 2)))
                        .addGap(29, 29, 29)
                        .addComponent(siparisverbutonu))
                    .addComponent(uyegirispaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 521, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitapsecenekleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapsecenekleriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapsecenekleriActionPerformed

    private void ekitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekitapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekitapActionPerformed

    private void uyeolbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeolbutonuActionPerformed
Uyeolmaekrani uyeolmaekrani=new Uyeolmaekrani();
uyeolmaekrani.setVisible(true);
    }//GEN-LAST:event_uyeolbutonuActionPerformed

    private void girisyapbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisyapbutonuActionPerformed
  String kullanici_adi=kullanici_adi_alani.getText();
       String parola=new String(parola_alani.getPassword());
        
        if (kullanıcı_listesi.size()==0) {
            JOptionPane.showMessageDialog(this, "Hicbir kullanici bulunmamaktadir.");
        }
        else{
        for(Kullanıcılar user:kullanıcı_listesi)
            if (user.getKullanici_adi().equals(kullanici_adi)&&user.getParola().equals(parola)) {
                JOptionPane.showMessageDialog(this, "Sitemize hosgeldiniz  "+kullanici_adi);
            return;
            }
            
        }
      
                JOptionPane.showMessageDialog(this,"Böyle bir kullanici bulunmamaktadir.Lutfen üye olun.");
    }//GEN-LAST:event_girisyapbutonuActionPerformed

    private void sepetbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepetbutonuActionPerformed
    Sepetim sepetimekrani =new Sepetim();
    sepetimekrani.setVisible(true);
    }//GEN-LAST:event_sepetbutonuActionPerformed

    private void siparisverbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparisverbutonuActionPerformed
        SiparisEkrani siparisekrani =new SiparisEkrani();
        
    siparisekrani.setVisible(true);
    }//GEN-LAST:event_siparisverbutonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        KitapSatisSitesi kitapSatisSitesiFrame=new KitapSatisSitesi();
           kitapSatisSitesiFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           kitapSatisSitesiFrame.setSize(950,800);
           kitapSatisSitesiFrame.setVisible(true);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapSatisSitesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapSatisSitesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapSatisSitesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapSatisSitesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ekitap;
    private javax.swing.JButton girisyapbutonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> kitapsecenekleri;
    private javax.swing.JTextField kullanici_adi_alani;
    private javax.swing.JPasswordField parola_alani;
    private javax.swing.JPanel registerpaneli;
    private javax.swing.JButton sepetbutonu;
    private javax.swing.JButton siparisverbutonu;
    private javax.swing.JPanel uyegirispaneli;
    private javax.swing.JButton uyeolbutonu;
    // End of variables declaration//GEN-END:variables
}
